#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payme.Movil
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class BaseDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEvento(Evento instance);
    partial void UpdateEvento(Evento instance);
    partial void DeleteEvento(Evento instance);
    partial void InsertCuenta(Cuenta instance);
    partial void UpdateCuenta(Cuenta instance);
    partial void DeleteCuenta(Cuenta instance);
    #endregion
		
		public BaseDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		
		
		
		public BaseDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
	
		public System.Data.Linq.Table<Evento> Evento
		{
			get
			{
				return this.GetTable<Evento>();
			}
		}
		
		public System.Data.Linq.Table<Cuenta> Cuenta
		{
			get
			{
				return this.GetTable<Cuenta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Evento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Identificador;
		
		private string _Nombre;
		
		private int _Valor;
		
		private string _Tipo;
		
		private System.DateTime _FechaHora;
		
		private string _Alerta;
		
		private string _IdCuenta;
		
		private EntityRef<Cuenta> _Cuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdentificadorChanging(int value);
    partial void OnIdentificadorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnValorChanging(int value);
    partial void OnValorChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnFechaHoraChanging(System.DateTime value);
    partial void OnFechaHoraChanged();
    partial void OnAlertaChanging(string value);
    partial void OnAlertaChanged();
    partial void OnIdCuentaChanging(string value);
    partial void OnIdCuentaChanged();
    #endregion
		
		public Evento()
		{
			this._Cuenta = default(EntityRef<Cuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificador", AutoSync=AutoSync.OnInsert, IsPrimaryKey=true, IsDbGenerated=true)]
		public int Identificador
		{
			get
			{
				return this._Identificador;
			}
			set
			{
				if ((this._Identificador != value))
				{
					this.OnIdentificadorChanging(value);
					this.SendPropertyChanging();
					this._Identificador = value;
					this.SendPropertyChanged("Identificador");
					this.OnIdentificadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor")]
		public int Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHora")]
		public System.DateTime FechaHora
		{
			get
			{
				return this._FechaHora;
			}
			set
			{
				if ((this._FechaHora != value))
				{
					this.OnFechaHoraChanging(value);
					this.SendPropertyChanging();
					this._FechaHora = value;
					this.SendPropertyChanged("FechaHora");
					this.OnFechaHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alerta", CanBeNull=false)]
		public string Alerta
		{
			get
			{
				return this._Alerta;
			}
			set
			{
				if ((this._Alerta != value))
				{
					this.OnAlertaChanging(value);
					this.SendPropertyChanging();
					this._Alerta = value;
					this.SendPropertyChanged("Alerta");
					this.OnAlertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCuenta", CanBeNull=false)]
		public string IdCuenta
		{
			get
			{
				return this._IdCuenta;
			}
			set
			{
				if ((this._IdCuenta != value))
				{
					if (this._Cuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCuentaChanging(value);
					this.SendPropertyChanging();
					this._IdCuenta = value;
					this.SendPropertyChanged("IdCuenta");
					this.OnIdCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Evento", Storage="_Cuenta", ThisKey="IdCuenta", OtherKey="IdCuenta", IsForeignKey=true)]
		public Cuenta Cuenta
		{
			get
			{
				return this._Cuenta.Entity;
			}
			set
			{
				Cuenta previousValue = this._Cuenta.Entity;
				if (((previousValue != value) 
							|| (this._Cuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cuenta.Entity = null;
						previousValue.Evento.Remove(this);
					}
					this._Cuenta.Entity = value;
					if ((value != null))
					{
						value.Evento.Add(this);
						this._IdCuenta = value.IdCuenta;
					}
					else
					{
						this._IdCuenta = default(string);
					}
					this.SendPropertyChanged("Cuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Cuenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdCuenta;
		
		private string _Nombre;
		
		private int _Valor;
		
		private string _Frecuencia;
		
		private System.DateTime _Rango1_D;
		
		private System.DateTime _Rango1_H;
		
		private System.DateTime _Rango2_D;
		
		private System.DateTime _Rango2_H;
		
		private EntitySet<Evento> _Evento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCuentaChanging(string value);
    partial void OnIdCuentaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnValorChanging(int value);
    partial void OnValorChanged();
    partial void OnFrecuenciaChanging(string value);
    partial void OnFrecuenciaChanged();
    partial void OnRango1_DChanging(System.DateTime value);
    partial void OnRango1_DChanged();
    partial void OnRango1_HChanging(System.DateTime value);
    partial void OnRango1_HChanged();
    partial void OnRango2_DChanging(System.DateTime value);
    partial void OnRango2_DChanged();
    partial void OnRango2_HChanging(System.DateTime value);
    partial void OnRango2_HChanged();
    #endregion
		
		public Cuenta()
		{
			this._Evento = new EntitySet<Evento>(new Action<Evento>(this.attach_Evento), new Action<Evento>(this.detach_Evento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCuenta", CanBeNull=false, IsPrimaryKey=true)]
		public string IdCuenta
		{
			get
			{
				return this._IdCuenta;
			}
			set
			{
				if ((this._IdCuenta != value))
				{
					this.OnIdCuentaChanging(value);
					this.SendPropertyChanging();
					this._IdCuenta = value;
					this.SendPropertyChanged("IdCuenta");
					this.OnIdCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor")]
		public int Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", CanBeNull=false)]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this.OnFrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._Frecuencia = value;
					this.SendPropertyChanged("Frecuencia");
					this.OnFrecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rango1_D")]
		public System.DateTime Rango1_D
		{
			get
			{
				return this._Rango1_D;
			}
			set
			{
				if ((this._Rango1_D != value))
				{
					this.OnRango1_DChanging(value);
					this.SendPropertyChanging();
					this._Rango1_D = value;
					this.SendPropertyChanged("Rango1_D");
					this.OnRango1_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rango1_H")]
		public System.DateTime Rango1_H
		{
			get
			{
				return this._Rango1_H;
			}
			set
			{
				if ((this._Rango1_H != value))
				{
					this.OnRango1_HChanging(value);
					this.SendPropertyChanging();
					this._Rango1_H = value;
					this.SendPropertyChanged("Rango1_H");
					this.OnRango1_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rango2_D")]
		public System.DateTime Rango2_D
		{
			get
			{
				return this._Rango2_D;
			}
			set
			{
				if ((this._Rango2_D != value))
				{
					this.OnRango2_DChanging(value);
					this.SendPropertyChanging();
					this._Rango2_D = value;
					this.SendPropertyChanged("Rango2_D");
					this.OnRango2_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rango2_H")]
		public System.DateTime Rango2_H
		{
			get
			{
				return this._Rango2_H;
			}
			set
			{
				if ((this._Rango2_H != value))
				{
					this.OnRango2_HChanging(value);
					this.SendPropertyChanging();
					this._Rango2_H = value;
					this.SendPropertyChanged("Rango2_H");
					this.OnRango2_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Evento", Storage="_Evento", ThisKey="IdCuenta", OtherKey="IdCuenta")]
		public EntitySet<Evento> Evento
		{
			get
			{
				return this._Evento;
			}
			set
			{
				this._Evento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Evento(Evento entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = this;
		}
		
		private void detach_Evento(Evento entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = null;
		}
	}
}
#pragma warning restore 1591
